### ISSUE TITLE
Building dodo

### ISSUE THREAD

**Issue by hjellinek** [devhawala/dodo#24]
Hi,

I've cloned the dodo repo with the idea of adding a key-value store or RDBMS to hold user information.  I'm using Gradle as a build tool.  I've been having to do some detective work to determine and locate the dependencies, or even the required JDK version, without a `build.gradle` or `pom.xml` to guide me. 

Can you add some documentation on how to build dodo, or, better yet, check in the script or tool you build it with?

Thanks.

**Comment by devhawala** [comment]
Hello,

it's a simple Eclipse-Project, importing the complete repo content into Eclipse with the Package-Explorer context-menu "Import..." then "Existing project into Workspace" gets you started in Eclipse.

The `readme.md` states somewhere that you need at least a JRE 8, same for the `.classpath` file of the Eclipse project ("JavaSE-1.8"), so any modern Java-JDK will do.

There is no required build tool, as there are almost no dependencies to other libraries or the like. The only external library is `jnetpcap.jar` (i don't even remember where i downloaded this from to copy it into the project's root) if you need to build the "NetHubGateway".

The jar-file is simply generated with  the Package-Explorer context-menu "Export..." on the project and then "Java" > "JAR file".

The `dist.zip` file is built by hand at the shell level: if you want to extend the distribution, you can start from the current `dist.zip`, add your files and specifically your new .jar-file.

Hope that helps
Hans

**Comment by hjellinek** [comment]
Hi,
Thanks for your quick reply.  I was hoping to find a Maven-style dependency declaration for the `jnetpcap.jar` library, but having the JAR file itself works too.

To start, I'll see if I can create a `build.gradle` file that builds the project JAR.
