### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by gcasa** [devhawala/dodo#6]
I have a Xerox 6085 and I would love to help with this.  Where is the Java source?

**Comment by devhawala** [comment]
Hello,

i don't understand: which Java source do you mean?

You just posted an issue in the Dodo project, which is my XNS services implementation in Java.

If you clone this github-repository to your machine at home, just import the project into Eclipse and there you are! (the Java sources for Dodo are in the directory "src" in this github-project)

If you are looking for the 6085 Mesa machine emulation also implemented in Java => see the [devhawala/dwarf](https://github.com/devhawala/dwarf) github-repository.

Greetings, Hans

**Comment by gcasa** [comment]
Hans, Sorry, I didn't see it. ;) Thanks, GC
